config/routes.rb
                      resources :myfsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfequipcs do
                      resources :myfequips do
      member do
        get "equip_img"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfstaffcs do
end end end

namespace :myfshop do resources :myfstaffcs do
                      resources :myfstaffs do
      member do
        get "staff_img"
      end
end end end

namespace :mygshop do resources :mygshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mygshop do resources :mygshops do
                      resources :mygmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygequipcs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygequipcs do
                      resources :mygequips do
      member do
        get "equip_img"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygstaffcs do
end end end

namespace :mygshop do resources :mygstaffcs do
                      resources :mygstaffs do
        member do
          get "staff_img"
        end
end end end

namespace :myhshop do resources :myhshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myhshop do resources :myhshops do
                      resources :myhmenucs
end end

namespace :myhshop do resources :myhmenucs do
                      resources :myhmenus
end end

namespace :myhshop do resources :myhmenus do
                      resources :myitems do
      member do
        get "item_img"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myhshop do resources :myhequipcs do
                      resources :myhequips do
      member do
        get "equip_img"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhstaffcs do
end end end

namespace :myhshop do resources :myhstaffcs do
                      resources :myhstaffs do
      member do
        get "staff_img"
      end
end end end



resources :acategories

resources :bcategories

resources :ccategories

resources :dcategories

resources :ecategories

resources :fcategories

resources :gcategories

resources :hcategories



resources :tops do
    resources :areas
end



resources :areas do
    resources :prefecs do
    member do
      get "topad", "newad", "recomad"
    end
end end



resources :prefecs do 
    namespace :ashop do resources :ashops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end

namespace :ashop do resources :ashops do
                    resources :pubmenus
end end

namespace :ashop do resources :ashops do
                    resources :pubimgs
end end

namespace :ashop do resources :ashops do
                    resources :amenucs
end end

namespace :ashop do resources :amenucs do
                    resources :amenus
end end

namespace :ashop do resources :amenus do
                    resources :foods do
end end end

namespace :ashop do resources :ashops do
                    resources :asmenucs
end end

namespace :ashop do resources :asmenucs do
                    resources :asmenus do
end end end

namespace :ashop do resources :ashops do
                    resources :admenucs
end end

namespace :ashop do resources :admenucs do
                    resources :admenus
end end

namespace :ashop do resources :admenus do
                    resources :drinks
end end

namespace :ashop do resources :ashops do
                    resources :atmenucs
end end

namespace :ashop do resources :atmenucs do
                    resources :atmenus
end end

namespace :ashop do resources :atmenus do
                    resources :atakeouts
end end



resources :prefecs do 
    namespace :bshop do resources :bshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end

namespace :bshop do resources :bshops do
                      resources :bmenucs
end end

namespace :bshop do resources :bshops do
                      resources :bsmenucs
end end



resources :prefecs do 
    namespace :cshop do resources :cshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :dshop do resources :dshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :eshop do resources :eshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :fshop do resources :fshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :gshop do resources :gshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :hshop do resources :hshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



namespace :asearch do resources :asshops do

  member do
      get "contact", "access", "time", "info", "pub"
    end

end end

namespace :asearch do resources :asshops do
                      resources :pubmenus
end end

namespace :asearch do resources :asshops do
                      resources :pubimgs
end end

namespace :asearch do resources :asshops do
                      resources :asmenucs
end end

namespace :asearch do resources :asmenucs do
                      resources :asmenus
end end

namespace :asearch do resources :asmenus do
                      resources :sfoods do
end end end

namespace :asearch do resources :asshops do
                      resources :assmenucs
end end

namespace :asearch do resources :assmenucs do
                      resources :assmenus do
    member do
      get "menuline"
    end
end end end

namespace :asearch do resources :assmenus do
                      resources :assub
end end

namespace :asearch do resources :asshops do
                      resources :adsmenucs
end end

namespace :asearch do resources :adsmenucs do
                      resources :adsmenus
end end

namespace :asearch do resources :adsmenus do
                      resources :sdrinks
end end

namespace :asearch do resources :asshops do
                      resources :atsmenucs
end end

namespace :asearch do resources :atsmenucs do
                      resources :atsmenus
end end

namespace :asearch do resources :atsmenus do
                      resources :astakeouts
end end



namespace :bsearch do resources :bsshops do

  member do
      get "contact", "access", "time", "info", "pub"
    end

end end

namespace :bsearch do resources :bsshops do
                      resources :bsmenucs
end end

namespace :bsearch do resources :bsshops do
                      resources :bssmenucs
end end

namespace :bsearch do resources :bsshops do
                      resources :bsequipcs
end end

namespace :bsearch do resources :bsequipcs do
                      resources :bsequips
end end

namespace :bsearch do resources :bsshops do
                      resources :bsstaffcs
end end

namespace :bsearch do resources :bsstaffcs do
                      resources :bsstaffs
end end



namespace :csearch do resources :csshops do

  member do
      get "contact", "access", "time", "info", "pub"
    end

end end

namespace :csearch do resources :csshops do
                      resources :csmenucs
end end

namespace :csearch do resources :csshops do
                      resources :cssmenucs
end end

namespace :csearch do resources :csshops do
                      resources :csequipcs
end end

namespace :csearch do resources :csequipcs do
                      resources :csequips
end end

namespace :csearch do resources :csshops do
                      resources :csstaffcs
end end

namespace :csearch do resources :csstaffcs do
                      resources :csstaffs
end end



namespace :dsearch do resources :dsshops do

  member do
      get "contact", "access", "time", "info", "pub"
    end

end end

namespace :dsearch do resources :dsshops do
                      resources :dsmenucs
end end

namespace :dsearch do resources :dsmenucs do
                      resources :dsmenus
end end

namespace :dsearch do resources :dsmenus do
                      resources :sautos do
end end end

namespace :dsearch do resources :dsshops do
                      resources :dssmenucs
end end

namespace :dsearch do resources :dsshops do
                      resources :dsequipcs
end end

namespace :dsearch do resources :dsequipcs do
                      resources :dsequips
end end

namespace :dsearch do resources :dsshops do
                      resources :dsstaffcs
end end

namespace :dsearch do resources :dsstaffcs do

app/models/top.rb
class Top < ApplicationRecord

	validates :name, presence: false
	
	has_many :areas
  
	  def to_param
	    name
	  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :set_top, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :create
  protect_from_forgery except: :updete

  def index
    $tops = Top.all
    render :layout => "app2"
  end

  def show
    redirect_to top_areas_path(top_id:$top)
  end

  def new
    $top = Top.new
  end

  def edit
  end

  def create
    $top = Top.new(top_params)

    respond_to do |format|
      if $top.save
        format.html { redirect_to tops_path, notice: 'Top was successfully created.' }
        format.json { render :show, status: :created, location: $top }
      else
        format.html { render :new }
        format.json { render json: $top.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if $top.update(top_params)
        format.html { redirect_to tops_path, notice: 'Top was successfully updated.' }
        format.json { render :show, status: :ok, location: $top }
      else
        format.html { render :edit }
        format.json { render json: $top.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    $top.destroy
    respond_to do |format|
      format.html { redirect_to tops_url, notice: 'Top was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_top
      $top = Top.where(:name => params[:id]).first
    end
    
    def top_params
      params.require(:top).permit(:name)
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/shared/top/_mnavi.html.erb


<div class="main-navi">

<div id="tab">

        <div class="tabs">
            <li rel="panel1" class="active">北海道</li>
            <li rel="panel2" class="active">東北</li>
            <li rel="panel3" class="active">関東</li>
            <li rel="panel4" class="active">中部</li>
        </div> 
   
              <div id="panel1" class="panel active">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"石狩") do %><li>石狩</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"空知") do %><li>空知</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"後志") do %><li>後志</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"渡島") do %><li>渡島</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"檜山") do %><li>檜山</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"胆振") do %><li>胆振</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"日高") do %><li>日高</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"上川") do %><li>上川</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"留萌") do %><li>留萌</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"宗谷") do %><li>宗谷</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"オホーツク") do %><li>オホーツク</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"十勝") do %><li>十勝</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"釧路") do %><li>釧路</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"根室") do %><li>根室</li><%end%>
                      </div>

              </div>

              <div id="panel2" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"青森県") do %><li>青森県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"秋田県") do %><li>秋田県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"岩手県") do %><li>岩手県</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"山形県") do %><li>山形県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"宮城県") do %><li>宮城県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"福島県") do %><li>福島県</li><%end%>
                      </div>

              </div>

              <div id="panel3" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"茨城県") do %><li>茨城県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"栃木県") do %><li>栃木県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"群馬県") do %><li>群馬県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"埼玉県") do %><li>埼玉県</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"東京都") do %><li>東京都</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"神奈川県") do %><li>神奈川県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"千葉県") do %><li>千葉県</li><%end%>
                      </div>

              </div>

              <div id="panel4" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"新潟県") do %><li>新潟県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"長野県") do %><li>長野県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"山梨県") do %><li>山梨県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"静岡県") do %><li>静岡県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"富山県") do %><li>富山県</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"岐阜県") do %><li>岐阜県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"愛知県") do %><li>愛知県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"石川県") do %><li>石川県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"福井県") do %><li>福井県</li><%end%>
                      </div>

              </div>


</div>



<div id="tab">

        <div class="tabs">
            <li rel="panel5" class="active">近畿</li>
            <li rel="panel6" class="active">中国</li>
            <li rel="panel7" class="active">四国</li>
            <li rel="panel8" class="active">九州</li>
        </div> 

              <div id="panel5" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"滋賀県") do %><li>滋賀県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"三重県") do %><li>三重県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"奈良県") do %><li>奈良県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"京都府") do %><li>京都府</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"大阪府") do %><li>大阪府</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"和歌山県") do %><li>和歌山県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"兵庫県") do %><li>兵庫県</li><%end%>
                      </div>

              </div>

              <div id="panel6" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"鳥取県") do %><li>鳥取県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"岡山県") do %><li>岡山県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"広島県") do %><li>広島県</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"島根県") do %><li>島根県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"山口県") do %><li>山口県</li><%end%>
                      </div>

              </div>

              <div id="panel7" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"愛媛県") do %><li>愛媛県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"香川県") do %><li>香川県</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"徳島県") do %><li>徳島県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"高知県") do %><li>高知県</li><%end%>
                      </div>

              </div>

              <div id="panel8" class="panel">

                      <div class="line">
                            <%= link_to area_prefecs_path(:area_id =>"福岡県") do %><li>福岡県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"大分県") do %><li>大分県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"宮崎県") do %><li>宮崎県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"佐賀県") do %><li>佐賀県</li><%end%>
                      </div>
                      <div class="linex">
                            <%= link_to area_prefecs_path(:area_id =>"熊本県") do %><li>熊本県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"鹿児島県") do %><li>鹿児島県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"長崎県") do %><li>長崎県</li><%end%>
                            <%= link_to area_prefecs_path(:area_id =>"沖縄県") do %><li>沖縄県</li><%end%>
                      </div>

              </div>

</div>

</div>

app/views/shared/top/_secondf.html.erb


<div id="second-feature">

        <div id="mainBox">

                    <div class="child">
                        <div class="img">
                            <%= link_to image_tag("video.jpg", { :alt =>'FIND　F9　find999'}), video_welcome_index_path %>
                        </div>
                        <h2 class="title">使い方</h2>              
                    </div>

                    <div class="child">
                        <div class="img">
                            <%= link_to image_tag("template/logo0", { :alt =>'FIND　F9　find999'}), allf9_welcome_index_path %>
                        </div>
                        <h2 class="title">各国のF9</h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= adimg1 %></div>
                        <h2 class="title"><%= adname1 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg2 %></div>
                        <h2 class="title"><%= @adname2 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg3 %></div>
                        <h2 class="title"><%= @adname3 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg4 %></div>
                        <h2 class="title"><%= @adname4 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg5 %></div>
                        <h2 class="title"><%= @adname5 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg6 %></div>
                        <h2 class="title"><%= @adname6 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg7 %></div>
                        <h2 class="title"><%= @adname7 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg8 %></div>
                        <h2 class="title"><%= @adname8 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg9 %></div>
                        <h2 class="title"><%= @adname9 %></h2>
                    </div>

                    <div class="child">
                        <div class="img"><%= @adimg10 %></div>
                        <h2 class="title"><%= @adname10 %></h2>
                    </div>
                    
        </div>

</div>