config/routes.rb
                      resources :myamenus
end end

namespace :myashop do resources :myamenus do
                      resources :myfoods do
    member do
      get "foodimg", "foodimg1", "foodimg2", "foodimg3"
    end
end end end

namespace :myashop do resources :myashops do
                      resources :myasmenucs
end end

namespace :myashop do resources :myasmenucs do
                      resources :myasmenus do
    member do
      get "menuline"
    end
end end end

namespace :myashop do resources :myashops do
                      resources :myadmenucs
end end

namespace :myashop do resources :myadmenucs do
                      resources :myadmenus
end end

namespace :myashop do resources :myadmenus do
                      resources :mydrinks
end end

namespace :myashop do resources :myashops do
                      resources :myatmenucs
end end

namespace :myashop do resources :myatmenucs do
                      resources :myatmenus
end end

namespace :myashop do resources :myatmenus do
                      resources :myatakeouts
end end


namespace :mybshop do resources :mybshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mybshop do resources :mybshops do
                      resources :mybmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mybshop do resources :mybshops do
                      resources :mybsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mybshop do resources :mybshops do
                      resources :mybequipcs do
      member do
        get "subedit"
      end
end end end

namespace :mybshop do resources :mybequipcs do
                      resources :mybequips do
        member do
          get "equip_img"
        end
end end end

namespace :mybshop do resources :mybshops do
                      resources :mybstaffcs do
end end end

namespace :mybshop do resources :mybstaffcs do
                      resources :mybstaffs do
      member do
        get "staff_img"
      end
end end end

namespace :mycshop do resources :mycshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mycshop do resources :mycshops do
                      resources :mycmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycsmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycequipcs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycequipcs do
                      resources :mycequips do
    member do
      get "equip_img"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycstaffcs do
end end end

namespace :mycshop do resources :mycstaffcs do
                      resources :mycstaffs do
    member do
      get "staff_img"
    end
end end end

namespace :mydshop do resources :mydshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mydshop do resources :mydshops do
                      resources :mydmenucs
end end

namespace :mydshop do resources :mydmenucs do
                      resources :mydmenus
end end

namespace :mydshop do resources :mydmenus do
                      resources :myautos do
    member do
      get "auto_img"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydsmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydequipcs do
    member do
      get "subedit"
    end
end end end

namespace :mydshop do resources :mydequipcs do
                      resources :mydequips do
    member do
      get "equip_img"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydstaffcs do
end end end

namespace :mydshop do resources :mydstaffcs do
                      resources :mydstaffs do
    member do
      get "staff_img"
    end
end end end


namespace :myeshop do resources :myeshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myeshop do resources :myeshops do
                      resources :myemenucs
end end

namespace :myeshop do resources :myemenucs do
  resources :myemenus
end end

namespace :myeshop do resources :myemenus do
                      resources :myouts do
      member do
       get "out_img"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myesmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myeequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myeshop do resources :myeequipcs do
                      resources :myeequips do
      member do
        get "equip_img"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myestaffcs do
end end end

namespace :myeshop do resources :myestaffcs do
                      resources :myestaffs do
      member do
        get "staff_img"
      end
end end end


namespace :myfshop do resources :myfshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myfshop do resources :myfshops do
                      resources :myfmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfequipcs do
                      resources :myfequips do
      member do
        get "equip_img"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfstaffcs do
end end end

namespace :myfshop do resources :myfstaffcs do
                      resources :myfstaffs do
      member do
        get "staff_img"
      end
end end end

namespace :mygshop do resources :mygshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mygshop do resources :mygshops do
                      resources :mygmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygequipcs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygequipcs do
                      resources :mygequips do
      member do
        get "equip_img"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygstaffcs do
end end end

namespace :mygshop do resources :mygstaffcs do
                      resources :mygstaffs do
        member do
          get "staff_img"
        end
end end end

namespace :myhshop do resources :myhshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myhshop do resources :myhshops do
                      resources :myhmenucs
end end

namespace :myhshop do resources :myhmenucs do
                      resources :myhmenus
end end

namespace :myhshop do resources :myhmenus do
                      resources :myitems do
      member do
        get "item_img"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myhshop do resources :myhequipcs do
                      resources :myhequips do
      member do
        get "equip_img"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhstaffcs do
end end end

namespace :myhshop do resources :myhstaffcs do
                      resources :myhstaffs do
      member do
        get "staff_img"
      end
end end end



resources :acategories

resources :bcategories

resources :ccategories

resources :dcategories

resources :ecategories

resources :fcategories

resources :gcategories

resources :hcategories



resources :tops do
    resources :areas
end



resources :areas do
    resources :prefecs do
    member do
      get "topad", "newad", "recomad"
    end
end end



resources :prefecs do 

app/models/dshop.rb
class Dshop < ApplicationRecord

	mount_uploader :topimage, PictureUploader
	mount_uploader :shopimage1, PictureUploader
	mount_uploader :shopimage2, PictureUploader
	mount_uploader :shopimage3, PictureUploader
    
    validates :user_id, presence: true
	validates :shopname, presence: true
	validates :top_id, presence: true
	validates :area_id, presence: true
	validates :prefec_id, presence: true
	validates :dcategory_id, presence: true

	belongs_to :top
	belongs_to :area
	belongs_to :prefec
	belongs_to :dcategory
	belongs_to :user

	has_many :dmenucs, dependent: :destroy
	has_many :dsmenucs, dependent: :destroy
	has_many :dequipcs, dependent: :destroy
	has_many :dstaffcs, dependent: :destroy
	has_many :dequips, dependent: :destroy
	has_many :dstaffs, dependent: :destroy

end

app/controllers/dshop/dshops_controller.rb
class Dshop::DshopsController < ApplicationController
before_action :set_dshop, only: [:get_area, :show, :edit, :home_edit, :img_edit, :contact_edit, :access_edit, :time_edit, :info_edit, :update, :destroy, :contact, :access, :time, :info]
protect_from_forgery except: :create
before_action :set_current_user
before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    $prefec = Prefec.where(:name => params[:prefec_id]).first
    $dshops = $prefec.dshops.all
    render :layout => "search"
  end

  def show
    $dshop = $prefec.dshops.where(:id => params[:id]).first
    render :layout => "shop_home"
  end

  def contact
    render :layout => "shop_contents"
  end

  def access
    render :layout => "shop_contents"
  end

  def time
    render :layout => "shop_contents"
  end

  def info
    render :layout => "shop_contents"
  end

  def pub
    render :layout => "shop_contents"
  end

  def create
  end

  def update
  end

  def destroy
  end

  def set_current_user
    @current_user = User.find_by(id: session[:username])
  end

  private

    def set_dshop
      $prefec = Prefec.where(:name => params[:prefec_id]).first
      $dshop = $prefec.dshops.where(:id => params[:id]).first
    end
    
    def dshop_params
      params.require(:dshop).permit(:top_id, :area_id, :prefec_id, :user_id, :dcategory_id, :category2, :category3, :bmenuc_id, :asmenuc_id, :topimage, :remove_topimage, :remove_shopimage1, :remove_shopimage2, :remove_shopimage3, :topimage_cache, :shopimage1_cache, :shopimage2_cache, :shopimage3_cache, :shopimage1, :shopimage2, :shopimage3, :shopname, :username, :phone1, :email1, :postnumb, :address, :bus, :train, :sunam1, :sunam2, :sunam3, :sunam4, :sunpm1, :sunpm2, :sunpm3, :sunpm4, :monam1, :monam2, :monam3, :monam4, :monpm1, :monpm2, :monpm3, :monpm4, :tuepm1, :tuepm2, :tuepm3, :tueam4, :tuepm1, :tuepm2, :tuepm3, :tuepm4, :wedam1, :wedpm2, :wedpm3, :wedpm4, :thuam1, :thuam2, :thuam3, :thuam4, :thupm1, :thupm2, :thupm3, :thupm4, :friam1, :friam2, :friam3, :friam4, :fripm1, :fripm2, :fripm3, :fripm4, :satam1, :satam2, :satam3, :satam4, :satpm1, :satpm2, :satpm3, :satpm4, :ititle1, :info1, :ititle2, :info2, :ititle3, :info3)
    end
end

app/views/shared/editer/dshop/_access.html.erb


<%= stylesheet_link_tag "creater/ashop/home", :media => "all" %>


<%= form_for($dshop, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>
    <% if dshop.errors.any? %>

          <div id="error_explanation">
              <h2><%= pluralize(dshop.errors.count, "error") %> prohibited this dshop from being saved:</h2>
                  <ul>
                    <% dshop.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
          </div>
      
     <% end %>
     
          <div class="section" id="page">

                <h1>アクセスを編集する</h1>

                <div id="field">
                  <%= form.label :postnumb do %><label for="labelx">郵便番号</label><% end %><br>
                  <%= form.text_field :postnumb, placeholder: '123-1234' %>
                </div>

                <div id="field">
                  <%= form.label :address do %><label for="labelx">住所</label><% end %><br>
                  <%= form.text_field :address, placeholder: '広島県東広島市西条町999-9' %>
                </div>

                <div id="field">
                  <%= form.label :bus do %><label for="labelx">最寄駅（バス）</label><% end %><br>
                  <%= form.text_field :bus, placeholder: '広島駅　徒歩10分' %>
                </div>

                <div id="field">
                  <%= form.label :train do %><label for="labelx">最寄駅（電車）</label><% end %><br>
                  <%= form.text_field :train, placeholder: '広島駅　徒歩10分' %>
                </div>

                    <%= form.hidden_field :topimage_cache %>
                    <%= form.hidden_field :shopimage1_cache %>
                    <%= form.hidden_field :shopimage2_cache %>
                    <%= form.hidden_field :shopimage3_cache %>

                <div id="actions">
                  <%= form.submit(:決定) %>
                </div>

                <%= link_to mydshop_mydshop_path(id:$dshop) do %>
                    <div id="eback">編集を中止する</div>
                <% end %>

          </div>

<% end %>

app/views/shared/editer/dshop/_contact.html.erb


<%= stylesheet_link_tag "creater/ashop/home", :media => "all" %>


<%= form_for($dshop, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>

    <% if dshop.errors.any? %>

          <div id="error_explanation">
              <h2><%= pluralize(dshop.errors.count, "error") %> prohibited this shop from being saved:</h2>
                  <ul>
                    <% dshop.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
          </div>
      
     <% end %>

          <div class="section" id="page">

              <h1>コンタクトを編集する</h1>

                  <div id="field">
                    <%= form.label :phone1 do %><label for="labelx">電話番号</label><% end %><br>
                    <%= form.text_field :phone1, placeholder: '000-000-0000' %>
                  </div>

                  <div id="field">
                    <%= form.label :email1 do %><label for="labelx">Eメール</label><% end %><br>
                    <%= form.text_field :email1, placeholder: 'find.999@find.com' %>
                  </div>

                    <%= form.hidden_field :topimage_cache %>
                    <%= form.hidden_field :shopimage1_cache %>
                    <%= form.hidden_field :shopimage2_cache %>
                    <%= form.hidden_field :shopimage3_cache %>

                <div id="actions"><%= form.submit(:決定) %></div>

                <%= link_to mydshop_mydshop_path(id:$dshop) do %>
                    <div id="eback">編集を中止する</div>
                <% end %>

          </div>

<% end %>

app/views/shared/editer/dshop/_home.html.erb


<%= stylesheet_link_tag "creater/ashop/home", :media => "all" %>
<%= stylesheet_link_tag "modal", :media => "all" %>
<%= javascript_include_tag "ashops" %>
<%= javascript_include_tag "modal" %>

<%= form_for($dshop, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>

  <% if dshop.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(dshop.errors.count, "error") %> prohibited this dshop from being saved:</h2>

          <ul>
            <% dshop.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          
    </div>
    
  <% end %>

        <div class="section" id="page">

            <h1>ホーム画面を編集する</h1>

                <div id="field">
                    <%= form.label :shopname do %><label for="labelx">:*店名 (必入力)</label><% end %><br>
                    <%= form.text_field :shopname, placeholder: 'エフナイン自動車' %>
                </div>

                <div id="field">
                    <%= form.label :top_id do %><label for="labelx">:*エリア (必入力)</label><% end %><br>
                    <%= form.collection_select :top_id, Top.order(:name), :id, :name, include_blank: true, :prompt => "選択してください" %>
                </div>

                <div id="field">
                    <%= form.label :area_id do %><label for="labelx">:*県 (必入力)</label><% end %><br>
                    <%= form.grouped_collection_select :area_id, Top.order(:name), :areas, :name, :id, :name, include_blank: true, :prompt => "選択してください" %>
                </div>

                <div id="field">
                    <%= form.label :prefec_id do %><label for="labelx">:*市町村 (必入力)</label><% end %><br>
                    <%= form.grouped_collection_select :prefec_id, Area.order(:name), :prefecs, :name, :id, :name, include_blank: true, :prompt => "選択してください" %>
                </div>

                <div id="field">
                    <%= form.label :dcategory_id do %><label for="labelx">:車・バイク・自転車カテゴリー (必入力)</label><% end %><br>
                    <%= form.collection_select :dcategory_id, Dcategory.order(:name), :id, :name, include_blank: true, :prompt => "選択してください" %>
                </div>

                <div id="field">
                    <%= form.collection_select :category2, Dcategory.order(:name), :id, :name, include_blank: true, :prompt => "選択してください" %>
                </div>
                
                <div id="field">
                    <%= form.collection_select :category3, Dcategory.order(:name), :id, :name, include_blank: true, :prompt => "選択してください" %>
                </div>

                <div id="field-pic">

                          <%= form.label :topimage do %><label for="labelx">:トップ画像</label><% end %><br>

                          <label for="labely"><%= form.file_field :topimage, id: :shop_topimage , id: "file" %></label>

                          <p id="imgdelete">*画像を削除する  <%= form.check_box :remove_topimage %></p>
                          <%= form.hidden_field :topimage_cache %><br>

                          <div id="thumb" onClick="$('#file').click()">
                            <% if dshop.topimage.present? %>
                              <div id="updimg"><%= image_tag dshop.topimage.thumb.url if $dshop.topimage? %></div> 
                            <% else %>
                              <div id="upimg"><%= image_tag("template/img") %></div>
                            <% end %>
                          </div>

                </div>

                  <%= link_to mydshop_mydshops_path do %>
                    <div id="eback">編集を中止する</div>
                  <% end %>
                  
                    <%= form.hidden_field :topimage_cache %>
                    <%= form.hidden_field :shopimage1_cache %>
                    <%= form.hidden_field :shopimage2_cache %>
                    <%= form.hidden_field :shopimage3_cache %>
                    
                <div id="actions">
                  <% if user_signed_in? %>
                    <li><%= form.submit(:決定) %></li>
                  <% else %>
                    <a class="js-modal-open" href=""><li><%= form.submit(:決定) %></li></a>

                    <div class="modal js-modal">
                        <div class="modal__bg js-modal-close"></div>
                        <div class="modal__content">

                            <p id="c0">この作業を続けるにはログインして下さい。</p>

                            <%= link_to new_user_session_path do %>
                              <li id="c1">ログイン（無料会員登録)</li>
                            <% end %></br>

                            <a class="js-modal-close" id="c2">閉じる</a>
                        </div><!--modal__inner-->
                    
                    </div><!--modal-->
                  <% end %>
                </div>

        </div>

<% end %>

<script>
    (function() {
  jQuery((function(_this) {
    return function() {
      var area;
      area = $('#dshop_area_id').html();
      console.log(area);
      return $('#dshop_top_id').change(function() {
        var options, top;
        top = $('#dshop_top_id :selected').text();
        options = $(area).filter("optgroup[label=" + top + "]").html();
        console.log(options);
        if (options) {
          return $('#dshop_area_id').html(options);
        } else {
          return $('#dshop_area_id').empty();
        }
      });
    };
  })(this));

}).call(this);

    (function() {
  jQuery((function(_this) {
    return function() {
      var prefec;
      prefec = $('#dshop_prefec_id').html();
      console.log(prefec);
      return $('#dshop_area_id').change(function() {
        var options, area;
        area = $('#dshop_area_id :selected').text();
        options = $(prefec).filter("optgroup[label=" + area + "]").html();
        console.log(options);
        if (options) {
          return $('#dshop_prefec_id').html(options);
        } else {
          return $('#dshop_prefec_id').empty();
        }
      });
    };
  })(this));

}).call(this);

</script>

<script>

$(function(){
  $fileField = $('#file')
 
  // 選択された画像を取得し表示
  $($fileField).on('change', $fileField, function(e) {
    file = e.target.files[0]
    reader = new FileReader(),
    $preview = $("#thumb");
 
    reader.onload = (function(file) {
      return function(e) {
        $preview.empty();
        $preview.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          class: "preview",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });
});

</script>

app/views/shared/editer/dshop/_info.html.erb


<%= stylesheet_link_tag "creater/ashop/info", :media => "all" %>


<%= form_for($dshop, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>

    <% if dshop.errors.any? %>

          <div id="error_explanation">
              <h2><%= pluralize(dshop.errors.count, "error") %> prohibited this dshop from being saved:</h2>
                  <ul>
                    <% dshop.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
          </div>
      
     <% end %>

          <div class="section" id="page">

              <h1>店舗情報を編集する</h1>

                  <div id="field">
                    <%= form.label :history do %><label for="labelx">：創業西暦</label><% end %><br>
                    <%= form.text_field :history, placeholder: '2010' %>
                  </div>

                  <div id="field">
                    <%= form.label :career1 do %><label for="labelx">：店長経歴1</label><% end %><br>
                    <%= form.text_field :career1, placeholder: '料理学校卒業' %>
                  </div>

                  <div id="field">
                    <%= form.label :career2 do %><label for="labelx">：店長経歴2</label><% end %><br>
                    <%= form.text_field :career2, placeholder: '調理師資格取得' %>
                  </div>

                  <div id="field">
                    <%= form.label :career3 do %><label for="labelx">：店長経歴３</label><% end %><br>
                    <%= form.text_field :career4, placeholder: '資格等' %>
                  </div>

                  <div id="field">
                    <%= form.label :career4 do %><label for="labelx">：店長経歴4</label><% end %><br>
                    <%= form.text_field :career4, placeholder: '資格等' %>
                  </div>

                  <div id="field">
                    <%= form.label :career5 do %><label for="labelx">：店長経歴5</label><% end %><br>
                    <%= form.text_field :career5, placeholder: '資格等' %>
                  </div>

                  <div id="field">
                    <%= form.label :recom1 do %><label for="labelx">：おすすめ料理1</label><% end %><br>
                    <%= form.text_field :recom1, placeholder: '唐揚げランチ' %>
                  </div>

                  <div id="field">
                    <%= form.label :recom2 do %><label for="labelx">：おすすめ料理2</label><% end %><br>
                    <%= form.text_field :recom2, placeholder: '豚キムチ丼' %>
                  </div>

                  <div id="field">
                    <%= form.label :recom3 do %><label for="labelx">：おすすめ料理3</label><% end %><br>
                    <%= form.text_field :recom3, placeholder: 'ホルモン定食' %>
                  </div>

                  <div id="field">
                    <%= form.label :recom4 do %><label for="labelx">：おすすめ料理4</label><% end %><br>
                    <%= form.text_field :recom4, placeholder: 'チキンカツ定食' %>
                  </div>

                  <div id="field">
                    <%= form.label :recom5 do %><label for="labelx">：おすすめ料理5</label><% end %><br>
                    <%= form.text_field :recom5, placeholder: 'ナポリタン' %>
                  </div>

                  <div id="field">
                    <%= form.label :iititle1 do %><label for="labelx">：題名1</label><% end %><br>
                    <%= form.text_field :iititle1, placeholder: 'お店のこだわり' %>
                  </div>

                  <div id="field">
                    <%= form.label :info1 do %><label for="labelx">：紹介文1</label><% end %><br>
                    <%= form.text_area :info1 %>
                  </div>

                  <div id="field">
                    <%= form.label :iititle2 do %><label for="labelx">：題名2</label><% end %><br>
                    <%= form.text_field :iititle2, placeholder: 'お店の特徴' %>
                  </div>

                  <div id="fieldy">
                    <%= form.label :info2 do %><label for="labelx">：紹介文2</label><% end %><br>
                    <%= form.text_area :info2 %>
                  </div>

                  <div id="field">
                    <%= form.label :iititle3 do %><label for="labelx">：題名3</label><% end %><br>
                    <%= form.text_field :ititle3, placeholder: 'お店のこだわり' %>
                  </div>

                  <div id="field">
                    <%= form.label :iinfo3 do %><label for="labelx">：紹介文3</label><% end %><br>
                    <%= form.text_area :info3 %>
                  </div>

                    <%= form.hidden_field :topimage_cache %>
                    <%= form.hidden_field :shopimage1_cache %>
                    <%= form.hidden_field :shopimage2_cache %>
                    <%= form.hidden_field :shopimage3_cache %>

                <div id="actions"><%= form.submit(:決定) %></div>

                <%= link_to mydshop_mydshop_path(id:$dshop) do %>
                    <div id="eback">編集を中止する</div>
                <% end %>

          </div>

<% end %>