config/routes.rb
Rails.application.routes.draw do

resources :pubimgs
resources :pubmenus
resources :likes

  
get 'welcome/index'
  
root 'welcome#index'


devise_for :admin_users, ActiveAdmin::Devise.config
ActiveAdmin.routes(self)
  

devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
}


resources :welcome do
    collection do
      get "video", "allf9", "usage", "sitemap", "mail", "aboutus", "code", "respon", "pp"
end end



resources :users do
    collection do
      get "profile", "myshop", "mywallet"
end end



namespace :myashop do resources :myashops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "img1_edit", "img2_edit", "img3_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myashop do resources :myashops do
                      resources :myamenucs
end end

namespace :myashop do resources :myamenucs do
                      resources :myamenus
end end

namespace :myashop do resources :myamenus do
                      resources :myfoods do
    member do
      get "foodimg", "foodimg1", "foodimg2", "foodimg3"
    end
end end end

namespace :myashop do resources :myashops do
                      resources :myasmenucs
end end

namespace :myashop do resources :myasmenucs do
                      resources :myasmenus do
    member do
      get "menuline"
    end
end end end

namespace :myashop do resources :myashops do
                      resources :myadmenucs
end end

namespace :myashop do resources :myadmenucs do
                      resources :myadmenus
end end

namespace :myashop do resources :myadmenus do
                      resources :mydrinks
end end

namespace :myashop do resources :myashops do
                      resources :myatmenucs
end end

namespace :myashop do resources :myatmenucs do
                      resources :myatmenus
end end

namespace :myashop do resources :myatmenus do
                      resources :myatakeouts
end end


namespace :mybshop do resources :mybshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mybshop do resources :mybshops do
                      resources :mybmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mybshop do resources :mybshops do
                      resources :mybsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mybshop do resources :mybshops do
                      resources :mybequipcs do
      member do
        get "subedit"
      end
end end end

namespace :mybshop do resources :mybequipcs do
                      resources :mybequips do
        member do
          get "equip_img"
        end
end end end

namespace :mybshop do resources :mybshops do
                      resources :mybstaffcs do
end end end

namespace :mybshop do resources :mybstaffcs do
                      resources :mybstaffs do
      member do
        get "staff_img"
      end
end end end

namespace :mycshop do resources :mycshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mycshop do resources :mycshops do
                      resources :mycmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycsmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycequipcs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycequipcs do
                      resources :mycequips do
    member do
      get "equip_img"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycstaffcs do
end end end

namespace :mycshop do resources :mycstaffcs do
                      resources :mycstaffs do
    member do
      get "staff_img"
    end
end end end

namespace :mydshop do resources :mydshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mydshop do resources :mydshops do
                      resources :mydmenucs
end end

namespace :mydshop do resources :mydmenucs do
                      resources :mydmenus
end end

namespace :mydshop do resources :mydmenus do
                      resources :myautos do
    member do
      get "auto_img"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydsmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydequipcs do
    member do
      get "subedit"
    end
end end end

namespace :mydshop do resources :mydequipcs do
                      resources :mydequips do
    member do
      get "equip_img"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydstaffcs do
end end end

namespace :mydshop do resources :mydstaffcs do
                      resources :mydstaffs do
    member do
      get "staff_img"
    end
end end end


namespace :myeshop do resources :myeshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myeshop do resources :myeshops do
                      resources :myemenucs
end end

namespace :myeshop do resources :myemenucs do
  resources :myemenus
end end

namespace :myeshop do resources :myemenus do
                      resources :myouts do
      member do
       get "out_img"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myesmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myeequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myeshop do resources :myeequipcs do
                      resources :myeequips do
      member do
        get "equip_img"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myestaffcs do
end end end

namespace :myeshop do resources :myestaffcs do
                      resources :myestaffs do
      member do
        get "staff_img"
      end
end end end


namespace :myfshop do resources :myfshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myfshop do resources :myfshops do
                      resources :myfmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfequipcs do
                      resources :myfequips do
      member do
        get "equip_img"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfstaffcs do
end end end

namespace :myfshop do resources :myfstaffcs do
                      resources :myfstaffs do
      member do
        get "staff_img"
      end
end end end

namespace :mygshop do resources :mygshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mygshop do resources :mygshops do
                      resources :mygmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygequipcs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygequipcs do
                      resources :mygequips do
      member do
        get "equip_img"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygstaffcs do
end end end

namespace :mygshop do resources :mygstaffcs do
                      resources :mygstaffs do
        member do
          get "staff_img"
        end
end end end

namespace :myhshop do resources :myhshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myhshop do resources :myhshops do
                      resources :myhmenucs
end end

namespace :myhshop do resources :myhmenucs do
                      resources :myhmenus
end end

namespace :myhshop do resources :myhmenus do
                      resources :myitems do
      member do
        get "item_img"
      end
end end end

namespace :myhshop do resources :myhshops do

app/controllers/mycshop/mycequipcs_controller.rb
class Mycshop::MycequipcsController < ApplicationController
    before_action :set_cequipc, only: [:show, :edit, :update, :destroy, :subedit]
    protect_from_forgery except: :create
    before_action :set_current_user
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def index
      $cshop = Cshop.where(:id => params[:mycshop_id]).first
      $cequipcs = $cshop.cequipcs.all
    end
  
    def show
      redirect_to mycshop_mycequipc_mycequips_path(mycequipc_id:$cequipc)
    end
  
    def new
      $cshop = Cshop.where(:id => params[:mycshop_id]).first
      $cequipc = $cshop.cequipcs.build
      render :layout => "shop/ashop/menu_edit"
    end
  
    def edit
      render :layout => "shop/ashop/menu_edit"
    end
  
    def create
      $cshop = Cshop.where(:id => params[:mycshop_id]).first
      $cequipc = $cshop.cequipcs.build(cequipc_params)
      $cequipc.user_id = current_user.id
  
      respond_to do |format|
        if $cequipc.save
          format.html { redirect_to mycshop_mycshop_path(id:$cshop), notice: 'Acategory was successfully created.' }
          format.json { render :show, status: :created, location: $cequipc }
        else
          format.html { render :new }
          format.json { render json: $cequipc.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if $cequipc.update(cequipc_params)
          format.html { redirect_to mycshop_mycshop_path(id:$cshop), notice: 'Acategory was successfully updated.' }
          format.json { render :show, status: :ok, location: $cequipc }
        else
          format.html { render :edit }
          format.json { render json: $cequipc.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    def destroy
      $cequipc.destroy
      respond_to do |format|
        format.html { redirect_to mycshop_mycshop_path(id:$cshop), notice: 'Top was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    private
  
      def set_cequipc
        $cshop = Cshop.where(:id => params[:mycshop_id]).first
        $cequipc = $cshop.cequipcs.where(:id => params[:id]).first
      end
      
      def cequipc_params
        params.require(:cequipc).permit(:cshop_id, :shopname, :user_id, :name)
      end
      
  end
  

app/controllers/mycshop/mycequips_controller.rb
class Mycshop::MycequipsController < ApplicationController
    before_action :set_cequip, only: [:show, :edit, :update, :destroy]
    protect_from_forgery except: :create
    before_action :set_current_user
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def index
      $cequipc = Cequipc.where(:id => params[:mycequipc_id]).first
      $cequips = $cequipc.cequips.all
      render :layout => "menu_category"
    end
  
    def show
      $cequipc = Cequipc.where(:id => params[:mycequipc_id]).first
      $cequips = $cequipc.cequips.all
      render :layout => "shop_equip"
    end
  
    def new
      $cequipc = Cequipc.where(:id => params[:mycequipc_id]).first
      $cequip = $cequipc.cequips.build
      render :layout => "shop/ashop/edit"
    end
  
    def edit
      $cequip.equip_img.cache! unless $cequip.equip_img.blank?
      render :layout => "shop/ashop/edit"
    end
  
    def equip_img
      $cequip.equip_img.cache! unless $cequip.equip_img.blank? 
      render :layout => "shop/ashop/edit"
    end
  
    def create
      $cequipc = Cequipc.where(:id => params[:mycequipc_id]).first
      $cequip = $cequipc.cequips.build(cequip_params)
      $cequip.user_id = current_user.id
  
      respond_to do |format|
        if $cequip.save
          format.html { redirect_to mycshop_mycequipc_mycequip_path(mycequipc_id:$cequipc, id:$cequip), notice: 'Grand was successfully created.' }
          format.json { render :show, status: :created, location: $cequip }
        else
          format.html { render :new }
          format.json { render json: $cequip.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if $cequip.update(cequip_params)
          format.html { redirect_to mycshop_mycequipc_mycequip_path(mycequipc_id:$cequipc, id:$cequip), notice: 'Menu was successfully updated.' }
          format.json { render :show, status: :ok, location: $cequip }
        else
          format.html { render :edit }
          format.json { render json: $cequip.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      $cequip.destroy
      respond_to do |format|
        format.html { redirect_to mycshop_mycequipc_mycequips_path(mycequipc_id:$cequipc), notice: 'Menu was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    private
      def set_cequip
        $cequipc = Cequipc.where(:id => params[:mycequipc_id]).first
        $cequip = $cequipc.cequips.where(:id => params[:id]).first
      end
  
      def cequip_params
        params.require(:cequip).permit(:cequipc_id, :user_id, :equip_img, :equip_img_cache, :name, :explain)
      end
  end
  

app/controllers/mycshop/mycstaffcs_controller.rb
class Mycshop::MycstaffcsController < ApplicationController
    before_action :set_cstaffc, only: [:show, :edit, :update, :destroy, :subedit]
    protect_from_forgery except: :create
    before_action :set_current_user
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def index
      $cshop = Cshop.where(:id => params[:mycshop_id]).first
      $cstaffcs = $cshop.cstaffcs.all
    end
  
    def show
      redirect_to mycshop_mycstaffc_mycstaffs_path(mycstaffc_id:$cstaffc)
    end
  
    def new
      $cshop = Cshop.where(:id => params[:mycshop_id]).first
      $cstaffc = $cshop.cstaffcs.build
      render :layout => "shop/ashop/menu_edit"
    end
  
    def edit
      render :layout => "shop/ashop/menu_edit"
    end
  
    def create
      $cshop = Cshop.where(:id => params[:mycshop_id]).first
      $cstaffc = $cshop.cstaffcs.build(cstaffc_params)
      $cstaffc.user_id = current_user.id
  
      respond_to do |format|
        if $cstaffc.save
          format.html { redirect_to mycshop_mycshop_path(id:$cshop), notice: 'Acategory was successfully created.' }
          format.json { render :show, status: :created, location: $cstaffc }
        else
          format.html { render :new }
          format.json { render json: $cstaffc.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if $cstaffc.update(cstaffc_params)
          format.html { redirect_to mycshop_mycshop_path(id:$cshop), notice: 'Acategory was successfully updated.' }
          format.json { render :show, status: :ok, location: $cstaffc }
        else
          format.html { render :edit }
          format.json { render json: $cstaffc.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      $cstaffc.destroy
      respond_to do |format|
        format.html { redirect_to mycshop_mycshop_path(id:$cshop), notice: 'Top was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    private
  
      def set_cstaffc
        $cshop = Cshop.where(:id => params[:mycshop_id]).first
        $cstaffc = $cshop.cstaffcs.where(:id => params[:id]).first
      end
      
      def cstaffc_params
        params.require(:cstaffc).permit(:cshop_id, :shopname, :user_id, :name)
      end
  end
  

app/views/mycshop/mycshops/show.html.erb
	<p id="notice"><%= notice %></p>

	<%= content_for(:head)  do %>
	    <title><%= page_title %></title>
	<% end %>

	<%= content_for(:home_edit)  do %>
        <div id="home_edit_btn">
			<%if user_signed_in? && $cshop.user_id == current_user.id %>
						<%= link_to img_edit_mycshop_mycshop_path, target:"_blank" do%><div id="edit">✐編集する</div><% end %>
			<% end %>
        </div>
    <% end %>

	<%= content_for(:main)  do %>
		<div id="main-feature">
			  <%= javascript_include_tag "shop" %>
			  <%= javascript_include_tag "slick.min" %>
  
					<div id="feature-wrapper">
						  <%= stylesheet_link_tag "slick/slick.css", :media => "screen" %>
						  <%= stylesheet_link_tag "slick/slick-theme.css", :media => "screen" %>

						  <ul class="slider">
								<% if $cshop.shopimage1.present? %>
									  <li><%= image_tag $cshop.shopimage1_url %><p><%= $cshop.shopname %></p></li>
								<% else %>
									  <li><%= image_tag "template/homepics" %><p><%= $cshop.shopname %></p></li>
								<% end %>
								<% if $cshop.shopimage2.present? %>
									  <li><%= image_tag $cshop.shopimage2_url %><p>image2</p></li>
								<% else %>
									  <li><%= image_tag "template/homepics" %><p>image2</p></li>
								<% end %>
								<% if $cshop.shopimage3.present? %>
									  <li><%= image_tag $cshop.shopimage3_url %><p>image3</p></li>
								<% else %>
									  <li><%= image_tag "template/homepics" %><p>image3</p></li>
								<% end %>
						  </ul>
					</div>

					<div id="top_af1">
                      <a href="https://px.a8.net/svt/ejp?a8mat=3B7GQK+94NAPE+50+2HN8K1" rel="nofollow">
                      <img border="0" width="728" height="90" alt="" src="https://www23.a8.net/svt/bgt?aid=200222588552&wid=001&eno=01&mid=s00000000018015057000&mc=1"></a>
                      <img border="0" width="1" height="1" src="https://www19.a8.net/0.gif?a8mat=3B7GQK+94NAPE+50+2HN8K1" alt="">
                	</div>
		</div>
	<% end %>

	<%= content_for(:idc1)  do %>
		<%if user_signed_in? && $cshop.user_id == current_user.id %>
			  <div id="ltop">
				  <%= link_to new_mycshop_mycshop_mycmenuc_path(mycshop_id:$cshop), target:"_blank" do%>
					  <p>⊕カテゴリーを追加する</p>
				  <% end %>
			  </div>
		 <%end%>

		 <% $cmenucs.each do |cmenuc| %>
				<div class="line">
					  <%= link_to mycshop_mycshop_mycmenuc_path(mycshop_id:$cshop, id:cmenuc) do %>
						  <li id="mc"><%= cmenuc.name %></li><br>
					  <%end%>
					  <%= link_to edit_mycshop_mycshop_mycmenuc_path(mycshop_id:$cshop, id:cmenuc), target:"_blank" do%>
						   <p id="mcedit">✐編集する</p>
					  <% end %>
				</div>
		<% end %>
	<% end %>

	<%= content_for(:idc2)  do %>
		<%if user_signed_in? && $cshop.user_id == current_user.id %>
			  <div id="ltop">
				  <%= link_to new_mycshop_mycshop_mycsmenuc_path(mycshop_id:$cshop), target:"_blank" do%>
					  <p>⊕カテゴリーを追加する</p>
				  <% end %>
			  </div>
		 <%end%>

		 <% $csmenucs.each do |csmenuc| %>
				<div class="line">
					  <%= link_to mycshop_mycshop_mycsmenuc_path(mycshop_id:$cshop, id:csmenuc) do %>
						  <li id="mc"><%= csmenuc.name %></li><br>
					  <%end%>
					  <%= link_to edit_mycshop_mycshop_mycsmenuc_path(mycshop_id:$cshop, id:csmenuc), target:"_blank" do%>
						   <p id="mcedit">✐編集する</p>
						<% end %>
				</div>
		<% end %>
	<% end %>

	<%= content_for(:idc3)  do %>
			<%if user_signed_in? && $cshop.user_id == current_user.id %>
					<div id="ltop">
						<%= link_to new_mycshop_mycshop_mycequipc_path(mycshop_id:$cshop), target:"_blank" do%>
							<p>⊕カテゴリーを追加する</p>
						<% end %>
					</div>
			<%end%>

			<% $cequipcs.each do |cequipc| %>
					<div class="line">
							<%= link_to mycshop_mycshop_mycequipc_path(mycshop_id:$cshop, id:cequipc) do %>
								<li id="mc"><%= cequipc.name %></li><br>
							<%end%>
							<%= link_to edit_mycshop_mycshop_mycequipc_path(mycshop_id:$cshop, id:cequipc), target:"_blank" do %>
								<p id="mcedit">✐編集する</p>
							<% end %>
					</div>
			<% end %>
	<% end %>

	<%= content_for(:idc4)  do %>
					<%if user_signed_in? && $cshop.user_id == current_user.id %>
							<div id="ltop">
								<%= link_to new_mycshop_mycshop_mycstaffc_path(mycshop_id:$cshop), target:"_blank" do %>
									<p>⊕カテゴリーを追加する</p>
								<% end %>
							</div>
					<%end%>

					<% $cstaffcs.each do |cstaffc| %>
							<div class="line">
									<%= link_to mycshop_mycshop_mycstaffc_path(mycshop_id:$cshop, id:cstaffc) do %>
										<li id="mc"><%= cstaffc.name %></li><br>
									<%end%>
									<%= link_to edit_mycshop_mycshop_mycstaffc_path(mycshop_id:$cshop, id:cstaffc), target:"_blank" do %>
										<p id="mcedit">✐編集する</p>
									<% end %>
							</div>
					<% end %>
	<% end %>


	<% @page_title = $cshop.shopname %> 
	<% @title = @page_title %>
	<% @edit = img_edit_mycshop_mycshop_path  %>  

	<% @main_navi_img1 =  image_tag("shopnavi/fee") %>
	<% @main_navi_img2 =  image_tag("shopnavi/fee") %>
	<% @main_navi_img3 =  image_tag("shopnavi/equip") %>
	<% @main_navi_img4 =  image_tag("shopnavi/staff") %>

	<% @main_navi_title1 =  "メインメニュー" %>
	<% @main_navi_title2 =  "サブメニュー" %>
	<% @main_navi_title3 =  "設備紹介" %>
	<% @main_navi_title4 =  "従業員・スタッフ" %>

    <% @navi4 = contact_mycshop_mycshop_path %>
	<% @navi5 = access_mycshop_mycshop_path %>
	<% @navi6 = info_mycshop_mycshop_path %>
	<% @navi7 = contact_mycshop_mycshop_path %>
	<% @navi8 = time_mycshop_mycshop_path %>
    
	<% @subnavi1 =  %>
	<% @subnavi2 =  %>

app/views/mycshop/mycshops/time_edit.html.erb
	
<%= content_for(:main)  do %>

	<%= form_for($cshop, :url => {:action => "update"}, :html => {:multipart => true}) do |form| %>
		<%= render 'shared/editer/cshop/time', cshop: $cshop %>
	<% end %>

<% end %>