config/routes.rb
namespace :mycshop do resources :mycshops do
                      resources :mycsmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycequipcs do
    member do
      get "subedit"
    end
end end end

namespace :mycshop do resources :mycequipcs do
                      resources :mycequips do
    member do
      get "equip_img"
    end
end end end

namespace :mycshop do resources :mycshops do
                      resources :mycstaffcs do
end end end

namespace :mycshop do resources :mycstaffcs do
                      resources :mycstaffs do
    member do
      get "staff_img"
    end
end end end

namespace :mydshop do resources :mydshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mydshop do resources :mydshops do
                      resources :mydmenucs
end end

namespace :mydshop do resources :mydmenucs do
                      resources :mydmenus
end end

namespace :mydshop do resources :mydmenus do
                      resources :myautos do
    member do
      get "auto_img"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydsmenucs do
    member do
      get "subedit"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydequipcs do
    member do
      get "subedit"
    end
end end end

namespace :mydshop do resources :mydequipcs do
                      resources :mydequips do
    member do
      get "equip_img"
    end
end end end

namespace :mydshop do resources :mydshops do
                      resources :mydstaffcs do
end end end

namespace :mydshop do resources :mydstaffcs do
                      resources :mydstaffs do
    member do
      get "staff_img"
    end
end end end


namespace :myeshop do resources :myeshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myeshop do resources :myeshops do
                      resources :myemenucs
end end

namespace :myeshop do resources :myemenucs do
  resources :myemenus
end end

namespace :myeshop do resources :myemenus do
                      resources :myouts do
      member do
       get "out_img"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myesmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myeequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myeshop do resources :myeequipcs do
                      resources :myeequips do
      member do
        get "equip_img"
      end
end end end

namespace :myeshop do resources :myeshops do
                      resources :myestaffcs do
end end end

namespace :myeshop do resources :myestaffcs do
                      resources :myestaffs do
      member do
        get "staff_img"
      end
end end end


namespace :myfshop do resources :myfshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myfshop do resources :myfshops do
                      resources :myfmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myfshop do resources :myfequipcs do
                      resources :myfequips do
      member do
        get "equip_img"
      end
end end end

namespace :myfshop do resources :myfshops do
                      resources :myfstaffcs do
end end end

namespace :myfshop do resources :myfstaffcs do
                      resources :myfstaffs do
      member do
        get "staff_img"
      end
end end end

namespace :mygshop do resources :mygshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :mygshop do resources :mygshops do
                      resources :mygmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygequipcs do
      member do
        get "subedit"
      end
end end end

namespace :mygshop do resources :mygequipcs do
                      resources :mygequips do
      member do
        get "equip_img"
      end
end end end

namespace :mygshop do resources :mygshops do
                      resources :mygstaffcs do
end end end

namespace :mygshop do resources :mygstaffcs do
                      resources :mygstaffs do
        member do
          get "staff_img"
        end
end end end

namespace :myhshop do resources :myhshops do

    member do
      get "contact", "access", "time", "info"
      get "home_edit", "img_edit", "contact_edit", "access_edit", "time_edit", "info_edit"
    end

    collection do
      get "home_new", "img_new"

end end end

namespace :myhshop do resources :myhshops do
                      resources :myhmenucs
end end

namespace :myhshop do resources :myhmenucs do
                      resources :myhmenus
end end

namespace :myhshop do resources :myhmenus do
                      resources :myitems do
      member do
        get "item_img"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhsmenucs do
      member do
        get "subedit"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhequipcs do
      member do
        get "subedit"
      end
end end end

namespace :myhshop do resources :myhequipcs do
                      resources :myhequips do
      member do
        get "equip_img"
      end
end end end

namespace :myhshop do resources :myhshops do
                      resources :myhstaffcs do
end end end

namespace :myhshop do resources :myhstaffcs do
                      resources :myhstaffs do
      member do
        get "staff_img"
      end
end end end



resources :acategories

resources :bcategories

resources :ccategories

resources :dcategories

resources :ecategories

resources :fcategories

resources :gcategories

resources :hcategories



resources :tops do
    resources :areas
end



resources :areas do
    resources :prefecs do
    member do
      get "topad", "newad", "recomad"
    end
end end



resources :prefecs do 
    namespace :ashop do resources :ashops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end

namespace :ashop do resources :ashops do
                    resources :pubmenus
end end

namespace :ashop do resources :ashops do
                    resources :pubimgs
end end

namespace :ashop do resources :ashops do
                    resources :amenucs
end end

namespace :ashop do resources :amenucs do
                    resources :amenus
end end

namespace :ashop do resources :amenus do
                    resources :foods do
end end end

namespace :ashop do resources :ashops do
                    resources :asmenucs
end end

namespace :ashop do resources :asmenucs do
                    resources :asmenus do
end end end

namespace :ashop do resources :ashops do
                    resources :admenucs
end end

namespace :ashop do resources :admenucs do
                    resources :admenus
end end

namespace :ashop do resources :admenus do
                    resources :drinks
end end

namespace :ashop do resources :ashops do
                    resources :atmenucs
end end

namespace :ashop do resources :atmenucs do
                    resources :atmenus
end end

namespace :ashop do resources :atmenus do
                    resources :atakeouts
end end



resources :prefecs do 
    namespace :bshop do resources :bshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end

namespace :bshop do resources :bshops do
                      resources :bmenucs
end end

namespace :bshop do resources :bshops do
                      resources :bsmenucs
end end



resources :prefecs do 
    namespace :cshop do resources :cshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :dshop do resources :dshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :eshop do resources :eshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :fshop do resources :fshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :gshop do resources :gshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end



resources :prefecs do 
    namespace :hshop do resources :hshops do

    member do
      get "contact", "access", "time", "info", "pub"
    end

end end end

app/controllers/myfshop/mybequipcs_controller.rb
class Mybshop::MybequipcsController < ApplicationController
    before_action :set_bequipc, only: [:show, :edit, :update, :destroy, :subedit]
    protect_from_forgery except: :create
    before_action :set_current_user
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def index
      $bshop = Bshop.where(:id => params[:mybshop_id]).first
      $bequipcs = $bshop.bequipcs.all
    end
  
    def show
      redirect_to mybshop_mybequipc_mybequips_path(mybequipc_id:$bequipc)
    end
  
    def new
      $bshop = Bshop.where(:id => params[:mybshop_id]).first
      $bequipc = $bshop.bequipcs.build
      render :layout => "shop/ashop/menu_edit"
    end
  
    def edit
      render :layout => "shop/ashop/menu_edit"
    end
  
    def create
      $bshop = Bshop.where(:id => params[:mybshop_id]).first
      $bequipc = $bshop.bequipcs.build(bequipc_params)
      $bequipc.user_id = current_user.id
  
      respond_to do |format|
        if $bequipc.save
          format.html { redirect_to mybshop_mybshop_path(id:$bshop), notice: 'Acategory was successfully created.' }
          format.json { render :show, status: :created, location: $bequipc }
        else
          format.html { render :new }
          format.json { render json: $bequipc.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if $bequipc.update(bequipc_params)
          format.html { redirect_to mybshop_mybshop_path(id:$bshop), notice: 'Acategory was successfully updated.' }
          format.json { render :show, status: :ok, location: $bequipc }
        else
          format.html { render :edit }
          format.json { render json: $bequipc.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    def destroy
      $bequipc.destroy
      respond_to do |format|
        format.html { redirect_to mybshop_mybshop_path(id:$bshop), notice: 'Top was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    private
  
      def set_bequipc
        $bshop = Bshop.where(:id => params[:mybshop_id]).first
        $bequipc = $bshop.bequipcs.where(:id => params[:id]).first
      end
      
      def bequipc_params
        params.require(:bequipc).permit(:bshop_id, :shopname, :user_id, :name)
      end
      
  end
  

app/controllers/myfshop/mybequips_controller.rb
class Mybshop::MybequipsController < ApplicationController
    before_action :set_bequip, only: [:show, :edit, :update, :destroy]
    protect_from_forgery except: :create
    before_action :set_current_user
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def index
      $bequipc = Bequipc.where(:id => params[:mybequipc_id]).first
      $bequips = $bequipc.bequips.all
      render :layout => "menu_category"
    end
  
    def show
      $bequipc = Bequipc.where(:id => params[:mybequipc_id]).first
      $bequips = $bequipc.bequips.all
      render :layout => "shop_equip"
    end
  
    def new
      $bequipc = Bequipc.where(:id => params[:mybequipc_id]).first
      $bequip = $bequipc.bequips.build
      render :layout => "shop/ashop/edit"
    end
  
    def edit
      $bequip.equip_img.cache! unless $bequip.equip_img.blank?
      render :layout => "shop/ashop/edit"
    end
  
    def equip_img
      $bequip.equip_img.cache! unless $bequip.equip_img.blank? 
      render :layout => "shop/ashop/edit"
    end
  
    def create
      $bequipc = Bequipc.where(:id => params[:mybequipc_id]).first
      $bequip = $bequipc.bequips.build(bequip_params)
      $bequip.user_id = current_user.id
  
      respond_to do |format|
        if $bequip.save
          format.html { redirect_to mybshop_mybequipc_mybequip_path(mybequipc_id:$bequipc, id:$bequip), notice: 'Grand was successfully created.' }
          format.json { render :show, status: :created, location: $bequip }
        else
          format.html { render :new }
          format.json { render json: $bequip.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if $bequip.update(bequip_params)
          format.html { redirect_to mybshop_mybequipc_mybequip_path(mybequipc_id:$bequipc, id:$bequip), notice: 'Menu was successfully updated.' }
          format.json { render :show, status: :ok, location: $bequip }
        else
          format.html { render :edit }
          format.json { render json: $bequip.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      $bequip.destroy
      respond_to do |format|
        format.html { redirect_to mybshop_mybequipc_mybequips_path(mybequipc_id:$bequipc), notice: 'Menu was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def set_current_user
      @current_user = User.find_by(id: session[:username])
    end
  
    private
      def set_bequip
        $bequipc = Bequipc.where(:id => params[:mybequipc_id]).first
        $bequip = $bequipc.bequips.where(:id => params[:id]).first
      end
  
      def bequip_params
        params.require(:bequip).permit(:bequipc_id, :user_id, :equip_img, :equip_img_cache, :name, :explain)
      end
  end
  

app/views/myfshop/myfstaffs/_form.html.erb
<%= form_for($fstaff, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>

  <% if fstaff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fstaff.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% fstaff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="section" id="page">

    <h1>料理を編集する</h1>

              <%= form.hidden_field :fstaffc_id %>

              <div id="field-pic">
                  <%= form.label :staff_img do %><label for="labelx">:トップ画像</label><% end %><br>

                  <label for="labely"><%= form.file_field :staff_img, id: :fstaff_staff_img , id: "file" %></label>

                  <div id="thumb" onClick="$('#file').click()">
                        <% if fstaff.staff_img.present? %>
                          <div id="updimg"><%= image_tag fstaff.staff_img.thumb.url if $fstaff.staff_img? %></div> 
                        <% else %>
                          <div id="upimg"><%= image_tag("template/img") %></div>
                        <% end %>
                  </div>
              </div>

              <div id="field">
                  <%= form.label :name do %><label for="labelx">:料理名</label><% end %><br>
                  <%= form.text_field :name, placeholder: '例）唐揚げ定食' %><br>
              </div>

              <%= form.hidden_field :staff_img_cache %>

              <div id="actions"><li><%= form.submit(:決定) %></li></div>

  <%= link_to myfshop_myfstaffc_myfstaffs_path do %><div id="eback">編集を中止する</div><% end %>

</div>

<% end %>

<script>

$(function(){
  $fileField = $('#file')
 
  // 選択された画像を取得し表示
  $($fileField).on('change', $fileField, function(e) {
    file = e.target.files[0]
    reader = new FileReader(),
    $preview = $("#thumb");
 
    reader.onload = (function(file) {
      return function(e) {
        $preview.empty();
        $preview.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          class: "preview",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });
});

</script>

app/views/myfshop/myfstaffs/_form2.html.erb
<%= form_for($fstaff, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>

  <% if fstaff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fstaff.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% fstaff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="section" id="page">

    <h1>料理を編集する</h1>

              <%= form.hidden_field :fstaff_id %>

                  <div id="field-pic">
                      <%= form.label :staff_img do %><label for="labelx">写真1</label><% end %><br>

                      <label for="labely"><%= form.file_field :staff_img, id: :fstaff_staff_img , id: "file1" %></label>

                      <div id="thumb1" onClick="$('#file1').click()">
                            <% if fstaff.staff_img.present? %>
                              <div id="updimg"><%= image_tag fstaff.staff_img.thumb.url if $fstaff.staff_img? %></div> 
                            <% else %>
                              <div id="upimg"><%= image_tag("template/img") %></div>
                            <% end %>
                      </div>
                  </div>

              <%= form.hidden_field :staff_img_cache %>

              <div id="actions"><li><%= form.submit(:決定) %></li></div>

              <%= link_to myfshop_myfstaffc_myfstaffs_path do %><div id="eback">編集を中止する</div><% end %>

</div>

<% end %>

<script>

$(function(){
  $fileField = $('#file1')
 
  // 選択された画像を取得し表示
  $($fileField).on('change', $fileField, function(e) {
    file = e.target.files[0]
    reader = new FileReader(),
    $preview = $("#thumb1");
 
    reader.onload = (function(file) {
      return function(e) {
        $preview.empty();
        $preview.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          class: "preview",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });
});

$(function(){
  $fileField = $('#file2')
 
  // 選択された画像を取得し表示
  $($fileField).on('change', $fileField, function(e) {
    file = e.target.files[0]
    reader = new FileReader(),
    $preview = $("#thumb2");
 
    reader.onload = (function(file) {
      return function(e) {
        $preview.empty();
        $preview.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          class: "preview",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });
});

$(function(){
  $fileField = $('#file3')
 
  // 選択された画像を取得し表示
  $($fileField).on('change', $fileField, function(e) {
    file = e.target.files[0]
    reader = new FileReader(),
    $preview = $("#thumb3");
 
    reader.onload = (function(file) {
      return function(e) {
        $preview.empty();
        $preview.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          class: "preview",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });
});

</script>


app/views/myfshop/myfstaffs/edit.html.erb
<%= content_for(:main)  do %>

	<%= form_for($fequip, :url => {:action => "update"}, :html => {:multipart => true}) do |form| %>

	<%= render 'form', fequip: $fequip %>

	<% end %>

<% end %>

app/views/myfshop/myfstaffs/index.html.erb
<%= content_for(:head)  do %>
    <%= stylesheet_link_tag "shophome/bshop/each_equip", :media => "all" %>
    <%= javascript_include_tag "city" %>
    <title><%= page_title %></title>

<% end %>

<%= content_for(:main)  do %>

  <%= link_to new_myfshop_myfstaffc_myfstaff_path do%><div id="new">＋設備を追加する</div><% end %>

  <% $fstaffs.each do |fstaff| %>

    <div id="each_equip">

        <div id="equip">
          
                <div id="top_pic"> 

                    <% if fstaff.staff_img.present? %>
                      <%= link_to image_tag(fstaff.staff_img_url), myfshop_myfstaffc_myfstaff_path(id:fstaff) %> 
                    <% else %>
                      <%= link_to image_tag("template/logo3"), myfshop_myfstaffc_myfstaff_path(id:fstaff) %> 
                    <% end %>
    
                </div>

                <P id="equip_name">
                    <% if fstaff.name.present? %>
                        <%= fstaff.name %>
                    <% else %>
                        （未入力）
                    <% end %>
                </P>

                <p id="edit">
                    <%= link_to '✐編集', edit_myfshop_myfstaffc_myfstaff_path(id:fstaff) %>
                </p>    

         </div>
    </div>


  <% end %>


<% end %>

app/views/myfshop/myfstaffs/new.html.erb
<%= content_for(:main)  do %>

	<%= form_for($fstaff, :url => {:action => "create"}, :html => {:multipart => true}) do |form| %>

	<%= render 'form', fstaff: $fstaff %>

	<% end %>

<% end %>

app/views/myfshop/myfstaffs/show.html.erb
<% @page_title = $fstaff.name %> 
<% @title2 = $fstaff.name %> 

<%= content_for(:edit) do %>
	<div id="edit">
    	<%= link_to '✐編集', staff_img_myfshop_myfstaffc_myfstaff_path(id:$fstaff) %>
    </div>    
<% end %>

<% $fstaffs.each do |fstaff| %>

	<% if $fstaff.staff_img.present? %>
		<% @image1 = image_tag $fstaff.staff_img_url %>
	<% else %>
		<% @image1 = image_tag "template/logo3" %>
	<% end %>

	<% if $fstaff.explain.present? %>
			<p><%= $fstaff.explain %></p>
	<% else %>
			<p>未入力</p>
	<% end %>

<% end %>

app/views/myfshop/myfstaffs/staff_img.erb
<%= content_for(:main)  do %>

	<%= form_for($fstaff, :url => {:action => "update"}, :html => {:multipart => true}) do |form| %>

	<%= render 'form2', fstaff: $fstaff %>

	<% end %>

<% end %>